### ISSUE TITLE
Unskip renovate/** branch

### ISSUE THREAD

**Issue by tjosepo** [gsoft-inc/wl-chromado#27]
We just had an issue where a patch version of a package broke our application, because the pacakge mistakenly updated a peer dependency to a higher major version. This breaking change was not detected by our other static analysis tools (typescript, eslint, pnpm, etc.)

Chromatic didn't run because the it was a Renovate branch.

I think Renovate branch should not be skipped, as dependencies can change the UI.

**Comment by patricklafrance** [comment]
Could you provide additional information please about the error and also a short explanation about why you believe it should be Chromatic who detecy this type of error? 🙏
